name: Release Package

on: [push, pull_request]
      
jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get full repository history
      run: |
        git remote add freedomscoops https://github.com/freedomscoops/freedomscoops.git
        git fetch --all
  
    - name: Install Prerequisites
      run: |
        sudo apt update
        sudo apt install python3-pil asciidoc unzip zip ruby dos2unix
        sudo gem install asciidoctor-pdf --pre
   
    - name: Install Deutex
      run: |
        git clone https://github.com/Doom-Utils/deutex.git
        cd deutex
        git checkout v5.2.1
        sudo apt install libpng-dev
        ./bootstrap
        ./configure
        make
        sudo make install

    - name: Build
      run: |
         make dist

    - name: Get current date
      id: date
      run: echo "date=$(date +'%m-%d-%Y')" >> $GITHUB_OUTPUT
      
    - name: Copy ZIP files from wads folder
      run: |
          mkdir -p release
          cp wads/*.zip release
          
    - name: Get upload URL
      id: get_upload_url
      run: echo "::set-output name=upload_url::${{ github.event.release.upload_url }}"
      

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/*.zip
          asset_name: ${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



